### ISSUE TITLE
Difference with the original mmd.js

### ISSUE THREAD

**Issue by bbottema** [bjb568/Markdown-HTML#6]
Hi, I saw you forked the original mmd.js and then copied it to Markdown-HTML. Since the original is not being developed anymore and you are still working on your copy, what exactly are the differences? Should I be using your version or not?

**Comment by bjb568** [comment]
This version works much better than the original and has more features. I think it's pretty safe to use this, tho there may be some bugs.

**Comment by bjb568** [comment]
[Here's a feature list/reference](http://devdoodle.net/formatting)
