### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lxg** [bjb568/Markdown-HTML#7]
I really love Markdown-HTML (and mmd.js for that matter), but the lack of a license makes it impossible to use them in public projects.

Would you mind adding a license to Markdown-HTML and mmd.js? (And, if you don't care too much about how your code is used, maybe something like MIT or even Public Domain would work for you?)

Update: It seems that the original author of this code is @p01, so I think I'll bother him, too, about the license.

**Comment by p01** [comment]
Hi,

I added MIT license to https://github.com/p01/mmd.js

Thanks for bringing this up.
HTH,

**Comment by bjb568** [comment]
Do you still want a license on this project too?

**Comment by lxg** [comment]
@bjb568 I think it would help ... even if the project is discontinued, it's a useful piece of code, and there are screnarios where it can be of great use.

**Comment by bjb568** [comment]
It's not discontinued. I'll add a license.

**Comment by bjb568** [comment]
Fixed in https://github.com/bjb568/Markdown-HTML/commit/4421ec6ac2441cb90476c64ce25d8c18a42dba04

**Comment by lxg** [comment]
Oops, sorry ... confused it with your fork of mmd.js. Thanks for adding a license!
